import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  MapIcon
} from '@heroicons/react/24/outline'
import PropertySideCard from "./map/components/PropertySideCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solstice Energy",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <>
          {children}
        </>



      </body>
    </html>
  );
}
